name: Deploy to Github Pages
on:
  workflow_run:
    workflows: ["Build & test"]
    branches: [main]
    types: 
      - completed

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - id: build
        name: Build
        run: pnpm run build

      - id: upload-artifact
        name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs:
      - build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deploy
        name: Deploy
        uses: actions/deploy-pages@v1