name: Deploy to Github Pages
on:
  workflow_run:
    workflows: ["Build & test"]
    branches: [main]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deploy
        name: Deploy
        uses: actions/deploy-pages@v1